name: 'PR to File'
description: 'Uses current PR and save it in a file'
inputs:
  git-token:
    description: 'Token to add changelog file'
    required: true
  committer-name:
    description: 'The name of the changelog file committer'
    required: false
    default: 'PR-to-file-bot'
  committer-email:
    description: 'The email of the changelog file committer'
    required: false
    default: 'pr-to-file@bot.com'
runs:
  using: 'node16'
  main: 'index.js'
